### ISSUE TITLE
Command-Q does not fully quit CPA ("Not Responding")

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#102] opened 2015-12-19 04:19 UTC
Quit CPA by clicking command-Q on Mac, 201512 (possibly twice if you are in a tool like Classifier; once for Classifier and once for the main GUI).  The windows all close, but dock icon stays alive and reports "Application not responding". 

I can Force Quit ok. And I think I waited a few minutes and it finally killed itself.  

Related to #22?

**Comment by daviddao** [comment] 2015-12-19 20:25
After investigating further following findings:
- It happens after opening the classifier window and closing it
- It is also a bug in the old CPA

I assume the reason is that the Classifier window is not closed correctly by wxPython

**Comment by jhung0** [comment] 2015-12-19 20:38
Maybe relevant
http://stackoverflow.com/questions/18918387/wxpython-program-quits-but-window-remaines-not-responding-after-calling-sys-exi

**Comment by LeeKamentsky** [comment] 2015-12-21 16:07
In some ways, the stackoverflow may be relevant. It's likely that starting the wx.App started a Mac thread and Python won't exit if there are threads still around. In the example, the code executes the statement, `app.exitMainLoop()`, but the code is not in a frame called from `app.MainLoop()`. There are messages to be processed, there is a thread that needs to receive a message in order to close, but the main loop isn't run, so the messages get left in the queue and the thread stays alive and the app doesn't close.

Some things to look at:
https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/CellProfiler-Analyst.py#L341

If the if/then path is taken, the OnClose routine will return without shutting down the javabridge, leaving the javabridge's thread hanging.

https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/CellProfiler-Analyst.py#L348

The javabridge is shut down in OnClose which is probably bad hygiene. Maybe the app could exit somehow without going through OnClose or some Java stuff might still happen after OnClose. I think this code should be moved to the `main()` function, after the event loop has been exited.

**Comment by daviddao** [comment] 2015-12-21 22:36
Some further findings:

>Some things to look at:
>https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/CellProfiler-Analyst.py#L341

>If the if/then path is taken, the OnClose routine will return without shutting down the javabridge, leaving     the javabridge's thread hanging.

if path is not taken. So I think this part of the code is fine.

> https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/CellProfiler-Analyst.py#L348

This seems to be the cause. Although javabridge doesn't throw an exception, the VM is not properly killed. I can still call the classifier after this part of the code.

Issue is fixed by uncommenting: https://github.com/CellProfiler/CellProfiler-Analyst/blob/master/CellProfiler-Analyst.py#L520

But it feels like an overkill.

**Comment by daviddao** [comment] 2015-12-21 23:53
You can download and test out the new version for mac [here] (https://drive.google.com/a/broadinstitute.com/file/d/0B2aYwrhHkhm4Wm8tdVZQMkd4V3c/view?usp=sharing) (only available for Broadies)

**Closed by daviddao** 2015-12-21 23:53 UTC
Labels: Bug, Mac OS
