### ISSUE TITLE
Latest CPA dmg locks on properties file load

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#170] opened 2016-02-29 20:25 UTC
I downloaded and installed CPA from the new cloudfront link today from here https://github.com/CellProfiler/CellProfiler-Analyst.  When I select a properties file and click OK, the dialog freezes and won't die unless I quit the application.

From Console:
```
2/29/16 3:18:44.612 PM CellProfiler Analyst[4290]: WARNING:root:PROPERTIES WARNING (image_channel_paths): This field name has been deprecated, use "image_path_cols" instead.
2/29/16 3:18:44.612 PM CellProfiler Analyst[4290]: WARNING:root:PROPERTIES WARNING (image_channel_files): This field name has been deprecated, use "image_file_cols" instead.
2/29/16 3:18:44.612 PM CellProfiler Analyst[4290]: WARNING:root:PROPERTIES WARNING (image_channel_names): This field name has been deprecated, use "image_names" instead.
2/29/16 3:18:44.649 PM CellProfiler Analyst[4290]: INFO:root:PROPERTIES: Using default image_buffer_size=1
2/29/16 3:18:44.649 PM CellProfiler Analyst[4290]: INFO:root:PROPERTIES: Using default tile_buffer_size=1
2/29/16 3:18:44.685 PM CellProfiler Analyst[4290]: INFO:root:PROPERTIES: Training set found at "/Users/dlogan/svn/ExampleImages/cpa_example/MyTrainingSet.txt"
2/29/16 3:18:44.762 PM CellProfiler Analyst[4290]: INFO:root:[MainThread] Connecting to the database...
2/29/16 3:18:44.765 PM CellProfiler Analyst[4290]: INFO:root:[MainThread] SQLite file: /Users/dlogan/CPA/CPA_DB_fdc81ae2949324125646274d008c261e.db
2/29/16 3:19:32.928 PM WindowServer[172]: CGError post_notification(const CGSNotificationType, void *const, const size_t, const bool, const CGSRealTimeDelta, const int, const CGSConnectionID *const, const pid_t): Timed out 0.250 second wait for reply from "CellProfiler Analyst" for synchronous notification type 109 (<unknown>) (CID 0x1d24b, PID 4290)
```

**Comment by daviddao** [comment] 2016-02-29 20:38
Strange, what Mac Version are you using? Is this the same machine you were using for the previous versions of CPA 2.2 ?

**Comment by dlogan** [comment] 2016-02-29 20:49
O'S 10.10. Yes, I can run a compiled version from a month ago.

**Comment by dlogan** [comment] 2016-03-03 20:41
Is there a file like on CellProfiler that I could try and clear for my machine? E.g. like [these instructions](http://forum.cellprofiler.org/t/cellprofiler-2-0-faq/664/19) to remove ~/Library/Preferences/CellProfilerLocal.cfg

```
"CellProfiler on the Mac crashes before I can do anything"

Close CellProfiler.
Launch Terminal and type
cd ~/Library/Preferences
ls -l CellProfilerLocal.cfg
and ensure the config exists

**Note the tilde in front of the Library folder - this indicates it is the Library folder in your USER directory, not the Library folder within the root folder of the whole machine)

Move the file to a safe, backup location (just in case we need it later):
mv ~/Library/Preferences/CellProfilerLocal.cfg ~/CellProfilerLocal.cfg.BACKUP 
which moves the file to your /Users/{Username} directory.

Re-launch CellProfiler
```

**Comment by daviddao** [comment] 2016-03-03 20:57
There is a file called "CellProfilerAnalystLocal.cfg" in ~/Library/Preferences

**Comment by daviddao** [comment] 2016-03-04 16:49
Ok, jane and I tried it out. It seems like CPA starts but you need to additionally click on the CPA logo in your menu bar to run it. Its strange.

**Comment by daviddao** [comment] 2016-03-04 16:50
Ok, @jhung0  and I tried it out. It seems like CPA works normally but you need to additionally click on the CPA logo in your menu bar in order for the CPA window to pop up. Its strange.

**Comment by dlogan** [comment] 2016-03-04 16:58
Wow, you're right!  The properties modal dialog is somehow not getting killed until the app is selected in the menu bar??

**Comment by daviddao** [comment] 2016-03-05 05:33
I could narrow the problem down to our automatic build machine. Neither building on windows nor on my machine has this problem. But still trying to solve it.

**Comment by daviddao** [comment] 2016-03-08 18:10
@LeeKamentsky found out that the reason could be that we somehow are not building CPA on our automatic build machine with Python packaged into the app.

**Comment by LeeKamentsky** [comment] 2016-03-08 18:26
I noticed that on David's machine, when he builds, there's a file in the DMG's Frameworks folder called Framework.python but not on the build machine. But admittedly, no clear reason why that would cause the problem.

**Comment by daviddao** [comment] 2016-03-08 20:37
@0x00B1 what is your view on it? Do you think that might be the cause?

**Comment by daviddao** [comment] 2016-03-29 00:25
[This](http://stackoverflow.com/questions/10184974/py2app-is-not-copying-the-python-framework-to-the-new-app-while-using-virutalenv) might solve the issue. 
**tld;** Py2app never copies system Python. We need to install a seperate python version and adjust the path on our build machine.

**Comment by daviddao** [comment] 2016-03-31 00:51
**Update** 
After reinstalling all dependencies (thanks Allen). We still have this issue on our mac build machine.
Even stranger: if we open the unix exec instead of double clicking the CPA logo, everything works fine. 

<img width="947" alt="screen shot 2016-03-30 at 8 49 33 pm" src="https://cloud.githubusercontent.com/assets/1241240/14162336/1b0b4c32-f6b9-11e5-98a6-c28472ec7eb8.png">

I am baffled.

**Comment by daviddao** [comment] 2016-04-15 14:52
Also, if I run stable unsigned CPA 2.2.1 (build on my machine) on the build machine, the build machine also causes it to freeze.

**Comment by daviddao** [comment] 2016-04-15 15:15
Also the build on my machine doesn't work anymore on Jane's machine but works fine on Mohammad's and my machine.

**Comment by daviddao** [comment] 2016-04-15 20:31
It has probably something to do with the signing process. After signing the app on my machine, uploading it on google drive and downloading it again, the properties loading screen freezes.

**Comment by shntnu** [comment] 2016-04-16 12:41
@daviddao 
See http://apple.stackexchange.com/questions/118598/macos-differences-between-running-a-bundled-app-and-running-the-bundles-execut
and note that 
```~/Desktop/CellProfiler\ Analyst.app/Contents/MacOS/CellProfiler\ Analyst``` does not have this problem whereas
```open ~/Desktop/CellProfiler\ Analyst.app``` does have this problem

the stackexchange discussion says that in the first case, the Info.plist file (which sets some env vars; possibly other side effects)  is not being read, and somehow that is resulting in the problem going away.

**Comment by daviddao** [comment] 2016-04-16 14:16
Thanks Shantanu, I will have a look into it later today!

**Comment by daviddao** [comment] 2016-04-16 22:07
The newest 'stable' version is signed. The frozen properties file problem only occurs, when one tries to start CPA for the first time (after moving it out of the .dmg file). Strange, but the best I could do. 

I looked into Info.plist but couldn't get more out of it.

**Comment by daviddao** [comment] 2016-04-18 19:38
@0x00B1 suggested 7328671 . Just tested it on the mac build. Issue is still there.

**Comment by daviddao** [comment] 2016-04-29 18:08
@0x00B1 thinks it might be this: http://stackoverflow.com/a/32492044/4490576

**Comment by 0x00B1** [comment] 2016-05-02 15:24
Fixed on nightly.

**Closed by 0x00B1** 2016-05-02 15:24 UTC
Labels: Bug, Mac OS

**Comment by jhung0** [comment] 2016-05-02 16:04
!!!

**Comment by daviddao** [comment] 2016-05-02 16:08
@AnneCarpenter @shntnu @LeeKamentsky @dlogan  🍰  🎉  🎈   We verified it! It is indeed fixed!!!!! It was a crazy deep bug in py2app! Hail to Allen! @AnneCarpenter This guy is amazing!

**Comment by shntnu** [comment] 2016-05-02 16:20
Bravo!
