### ISSUE TITLE
Dimension Reduction Button?

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#90] opened 2015-12-09 14:33 UTC
I don't know what the dimension button is supposed to do (there's no text when hovering over it), but on my training set of a few hundred samples and features, when I press the button it says it will take > 6 hours to finish. How about we remove it or replace it?

**Comment by braymp** [comment] 2015-12-09 14:46
Possible duplicate of #14?

**Comment by daviddao** [comment] 2015-12-09 15:12
I agree, it is definitely reproducible. I wonder how many people are using this functionality. Maybe we can just do a random projection? - I will have a look at the source.

**Comment by jhung0** [comment] 2015-12-09 15:22
Also not sure how people would use it. Would they want the option to "undo" it and get back to the original features? Do they want to see what happens after pressing the button/ what features are left? How much control should there be over the reduction?

**Comment by daviddao** [comment] 2015-12-09 15:38
From issue #14:
> We will try it and see if the problem is reproducible and easily fixable. If it seems to work for most people, we might add a warning that this is poorly tested functionality. If it doesn't work for anyone and can't be easily fixed we'll remove it. - @ljosa 

@ljosa what were your conclusions?

**Comment by ljosa** [comment] 2015-12-12 08:50
I never got around to investigating #14. Is this the SVM code that was contributed? I doubt it has ever been used.

**Comment by daviddao** [comment] 2015-12-14 20:16
Ok thanks. I (temporarily) removed it from the classifier panel in CPA with  b5e0328 . We will probably either try to improve the runtime (random projection, optimizing code) or just keep it removed.

**Comment by AnneCarpenter** [comment] 2015-12-15 06:10
Do we need a deep discussion on whether feature reduction is necessary as a pre-processing step for some of the machine learning methods we now have? It wasn’t so useful for Gentle Boosting so it’s understandable this was not really a supported feature when that was (almost) the only option. But now that we have many other options - do those options include feature reduction within them, or do we need to offer this as pre-processing?

**Comment by daviddao** [comment] 2015-12-16 15:29
Yes, I think we need to have this discussion for CPA - however it will go beyond the scope of this issue. Hence I opened a new issue #101 for that.

**Closed** 2016-01-20 22:22 UTC
