### ISSUE TITLE
Label truncated/mismatched in saved training set

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler-Analyst#11] opened 2012-02-15 14:57 UTC
The label of one of the training sets is truncated: it says "StrongERSy" although the rest of the lines refer to WeakERSyto. 

I'm not sure how this could have happened. It is of course possible that someone has opened the file in a text editor and been unluckly. Go ahead and close if you can't find anything suspicious in the code. 

The training set is /imaging/analysis/2010_04_30_HDAC_Inhibitors_Koehler_Labknockdowns/Combined plates/StrongERSyto_TrainingSet.txt. The first few lines: 

# Training set created while using properties: Z:\2010_04_30_HDAC_Inhibitors_Koehler_Lab\knockdowns\Combined plates\Knockdowns_combinedplates.properties.txt 
label StrongERSy WeakERSyto 
StrongERSyto 0 691 14 232 231 
StrongERSyto 0 651 48 269 263 

Originally entered 2011-07-14. I have since edited the file to fix the problem.

**Comment by daviddao** [comment] 2015-11-30 20:43
I can't reproduce it. Hence I would close this issue, but still keep an eye out - and reopen if necessary.

**Closed** 2015-12-07 23:18 UTC
Labels: Bug
