### ISSUE TITLE
Classifier: "Check features" produces ValueError

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#152] opened 2016-01-26 20:54 UTC
Just for fun, I tried the "Check features" item under Advanced, not knowing what it did. I had loaded a training set, trained it (RandomForest), and got this error.

```
An error occurred in the program:
ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required.

Traceback (most recent call last):
  File "C:\Trunk\cellProfiler-analyst\cpa\classifier.py", line 1955, in OnFeatureSelect
    selector.fit(self.trainingSet.values)
  File "C:\Python27\lib\site-packages\sklearn\feature_selection\variance_threshold.py", line 64, in fit
    X = check_array(X, ('csr', 'csc'), dtype=np.float64)
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 415, in check_array
    context))
```

**Comment by jhung0** [comment] 2016-04-26 20:55
Is this still an issue?

**Comment by braymp** [comment] 2016-04-27 08:33
No, it seems to work now.

**Comment by dlogan** [comment] 2016-08-05 17:24
I just received nearly the same error with  Advanced > Check Features using a recent Mac Nightly from 2016_08_03:

```
An error occurred in the program:
ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required.

Traceback (most recent call last):
  File "cpa\classifier.pyc", line 1974, in OnFeatureSelect
  File "sklearn\feature_selection\variance_threshold.pyc", line 64, in fit
  File "sklearn\utils\validation.pyc", line 415, in check_array
```

**Comment by dlogan** [comment] 2016-08-05 17:30
Hmm, then I retrained, clicked Evaluate, and then tried Check Features again and it worked.  I saw the error again, but I can't reliable reproduce. 😵

**Comment by DavidStirling** [comment] 2021-04-05 20:24
Looks like this is fixed now.

**Closed by DavidStirling** 2021-04-05 20:24 UTC
Labels: Bug, ready
